language: objective-c
osx_image: xcode7.3
before_install:
  - gem install xcpretty
  - gem install cocoapods
  - pod repo update
script:
  - cd Example
  - pod install
  - xcodebuild -version
  - xcodebuild -workspace AwaitKitExample.xcworkspace -scheme AwaitKitTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6,OS=9.0" -configuration Release GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=YES test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
